version: '3'
services:
  redis:
    image: redis:latest
    # image: redis:6.2-alpine
    restart: always
    command: redis-server --save 60 1
    volumes:
      - ./node-server/cache/redis:/data
  node-server:
    # build: ./node-server
    image: 0xkaz/weavedb-node-server:latest
    ports:
      - "9090:9090"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./node-server/cache:/weavedb/cache
    depends_on:
      - redis
    env_file: .env

  envoy:
    # build: ./envoy
    image: 0xkaz/weavedb-envoy:latest
    ports:
      - "8080:8080"    